### ISSUE TITLE
Require 'rvm1/capistrano3' breaks non-rvm deploy environments

### ISSUE THREAD

**Issue by luckyruby** [rvm/rvm1-capistrano3#30]
I have a setup where rvm is used for staging but not in production. If I place `require 'rvm1/capistrano3'` in my Capfile, my production deploy script craps out with

```
bundle stdout: Nothing written
bundle stderr: Can not find rvm in '/home/deployer/.rvm'.
```

**Comment by Javed43** [comment]
I got the same error. Could you please tel me how to rvm1 version is 1.3.2.2.

cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as jh15785@54.165.209.56: bundle exit status: 102
bundle stdout: Can not find rvm in '/home/jh15785/.rvm'.
bundle stderr: Nothing written
/home/javed/.rvm/gems/ruby-2.2.1@SD/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:16:in `rescue in block (2 levels) in execute'
/home/javed/.rvm/gems/ruby-2.2.1@SD/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
SSHKit::Command::Failed: bundle exit status: 102
bundle stdout: Can not find rvm in '/home/jh15785/.rvm'.
bundle stderr: Nothing written
/home/javed/.rvm/gems/ruby-2.2.1@SD/gems/sshkit-1.7.1/lib/sshkit/command.rb:95:in `exit_status='
/home/javed/.rvm/gems/ruby-2.2.1@SD/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:179:in `block in _execute'
/home/javed/.rvm/gems/ruby-2.2.1@SD/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:133:in `tap'
/home/javed/.rvm/gems/ruby-2.2.1@SD/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:133:in `_execute'
/home/javed/.rvm/gems/ruby-2.2.1@SD/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:66:in `execute'
/home/javed/.rvm/gems/ruby-2.2.1@SD/gems/capistrano-bundler-1.1.4/lib/capistrano/tasks/bundler.cap:35:in `block (5 levels) in <top (required)>'
/home/javed/.rvm/gems/ruby-2.2.1@SD/gems/sshkit-1.7.1/lib/sshkit/backends/abstract.rb:85:in `with'
/home/javed/.rvm/gems/ruby-2.2.1@SD/gems/capistrano-bundler-1.1.4/lib/capistrano/tasks/bundler.cap:26:in `block (4 levels) in <top (required)>'
/home/javed/.rvm/gems/ruby-2.2.1@SD/gems/sshkit-1.7.1/lib/sshkit/backends/abstract.rb:77:in `within'
/home/javed/.rvm/gems/ruby-2.2.1@SD/gems/capistrano-bundler-1.1.4/lib/capistrano/tasks/bundler.cap:25:in `block (3 levels) in <top (required)>'
/home/javed/.rvm/gems/ruby-2.2.1@SD/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/home/javed/.rvm/gems/ruby-2.2.1@SD/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `run'
/home/javed/.rvm/gems/ruby-2.2.1@SD/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
Tasks: TOP => deploy:updated => bundler:install
The deploy has failed with an error: Exception while executing as jh15785@54.165.209.56: bundle exit status: 102
bundle stdout: Can not find rvm in '/home/jh15785/.rvm'.
bundle stderr: Nothing written
** Invoke deploy:failed (first_time)
** Execute deploy:failed
