### ISSUE TITLE
Does not seem to use gemset

### ISSUE THREAD

**Issue by i-arindam** [rvm/rvm1-capistrano3#41]
I am trying to deploy a Rails 4 app to a VPS.

My Capfile, Gemfile, deploy.rb are in [this gist](https://gist.github.com/i-arindam/18fbf79da5adef10baaf)

On cap production deploy it fails bundle install step, because it doesn't use the gemset, and keeps saying gem not found.

The relevant output from `cap`

```
INFO[90fcd8c1] Running /tmp/domain_spam_checker/rvm-auto.sh 2.1.2 bundle exec gem install --file Gemfile on 162.221.181.224
DEBUG[90fcd8c1] Command: cd /home/deployer/domain_spam_checker/releases/20140922153958 && /tmp/domain_spam_checker/rvm-auto.sh 2.1.2 bundle exec gem install --file Gemfile
DEBUG[90fcd8c1]     [31mCould not find i18n-0.6.11 in any of the sources[0m
DEBUG[90fcd8c1]     [33mRun 'bundle install' to install missing gems.[0m
cap aborted!
```

...

`Tasks: TOP => deploy => rvm1:install:gems`

How to mention the gemset name to use somewhere in the setup files ?

How to get rvm1/cap3 to pickup or create the gemset ?

/cc @mpapis 
I'm using a separate gemset from `@global` and want all my gems to be in that gemset. Sandboxing in a way. Is that possible with this gem?

**Comment by devmod** [comment]
How does rvm1-capistrano3 picks the gemset on which to install the gems?
I have a similar issue and knowing this would help me continue debugging.

**Comment by mpapis** [comment]
by default a project file is used: http://rvm.io/workflow/projects - you can force it with: https://github.com/rvm/rvm1-capistrano3#configuration

**Comment by devmod** [comment]
I have already a .ruby-gemset and it doesn't seem to be picked up. Maybe it works only with older .rvmrc? 
Also, I had read the readme, but it doesnt really say how to force it. It just says the gems will be installed into the 'gemset'

**Comment by mpapis** [comment]
.ruby-gender works only with .ruby-version as for forcing gemset it can be
given as part of ruby version like: 2.2.1@gemset
