### ISSUE TITLE
cannot load such file -- rvm1-capistrano3

### ISSUE THREAD

**Issue by diegodillenburg** [rvm/rvm1-capistrano3#50]
Hi there, 

I'm getting this error while trying to require the gem in Capfile:
cannot load such file -- rvm1-capistrano3 when trying to "cap production deploy"

Capfile:
```ruby   
    require 'rvm1-capistrano3'
```
also have it on my Gemfile:
```ruby   
group :development do
	gem 'capistrano-rails',  '~> 1.1.1'
	gem 'capistrano-passenger'
    gem  'rvm1-capistrano3', :require => false
end
```

**Comment by mpapis** [comment]
closing as there was no feedback in two weeks, please let me know if you can provide more details and I will reopen
