### ISSUE TITLE
Warnings after upgrading to Ruby 2.2

### ISSUE THREAD

**Issue by rhomeister** [rvm/rvm1-capistrano3#53]
Hi @mpapis,

I'm getting the following warnings after the upgrade to Ruby 2.2. Is this something to worry about?

Warning: PATH set to RVM ruby but GEM_HOME and/or GEM_PATH not set, see:
    https://github.com/wayneeseguin/rvm/issues/3212

Warning! PATH is not properly set up, $GEM_HOME is not set,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.2.0'

**Comment by mpapis** [comment]
Hi Ruben, please [gist](https://gist.github.com) all output and code you got. btw. have you seen this => http://niczsoft.com/2015/02/changes-in-my-open-source-life/ ?

**Comment by rhomeister** [comment]
Hi mpapis, thanks for sharing your blog post. I've been there too, and unfortunately I know the feeling. Good that you're setting boundaries. The issue I opened seems to be only a warning, so it doesn't have high priority. I was just hoping that you might recognise it and tell me if it is something to worry about. If not, please close it and do something that doesn't drain your energy ;).

**Comment by mpapis** [comment]
Read the warning and check your environment variables, this warning is there you to show you your system misconfiguration.
