### ISSUE TITLE
can't find bundle command in deploy

### ISSUE THREAD

**Issue by masarakki** [rvm/rvm1-capistrano3#57]
Becase of `rvm` is no longer install `bundler` as default, `capistrano-bundler`'s `bundler install` can't work.
So, we should install `bundler` between installing ruby and bundle install,
but I can't decide who should take responsibility of this task.
`rvm1-capistrano3` ? or `capistrano-bundler` ? or something else?
I think it should be `rvm1-capistrano3`'s task.

fundamentally, I can't understand why `rvm` remove `bundler` from default gemsets.

**Comment by rhomeister** [comment]
Try adding this to your deploy.rb:

```
namespace :rvm1 do # https://github.com/rvm/rvm1-capistrano3/issues/45
  desc "Install Bundler"
  task :install_bundler do
    on release_roles :all do
      execute "cd #{release_path} && #{fetch(:rvm1_auto_script_path)}/rvm-auto.sh . gem install bundler"
    end
  end
end

after 'rvm1:install:ruby', 'rvm1:install_bundler'
```

**Comment by Overload119** [comment]
Thank you rhomeister!
