### ISSUE TITLE
Debug tips needed for my unicorn /etc/init.d script

### ISSUE THREAD

**Issue by jesperronn** [rvm/rvm1-capistrano3#73]
I'm using rvm1-capistrano3 in combination with https://github.com/bruno-/capistrano-unicorn-nginx

(actually [my own fork of it](https://github.com/jesperronn/capistrano-unicorn-nginx-ami), since it's modified to fit Amazon Linux )

I really could need some troubleshooting tips for an example of some working init.d scripts

In particular, I am constantly running into errors like 

```
INFO [b00f1dd1] Running /usr/bin/env sudo service unicorn_my_application_ci start as deployer@my-application-test.nine.dk
DEBUG [b00f1dd1] Command: /usr/bin/env sudo service unicorn_my_application_ci start
DEBUG [b00f1dd1] 	/etc/init.d/unicorn_my_application_ci: line 37: kill: (23555) - No such process
DEBUG [b00f1dd1] 	
Warning: PATH set to RVM ruby but GEM_HOME and/or GEM_PATH not set, see:
    https://github.com/wayneeseguin/rvm/issues/3212

DEBUG [b00f1dd1] 	Warning! PATH is not properly set up, $GEM_HOME is not set,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.3.0'.
DEBUG [b00f1dd1] 	master failed to start, check stderr log for details
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deployer@my-application-test.nine.dk: sudo exit status: 1
sudo stdout: Nothing written
sudo stderr: /etc/init.d/unicorn_my_application_ci: line 37: kill: (23555) - No such process

Warning: PATH set to RVM ruby but GEM_HOME and/or GEM_PATH not set, see:
    https://github.com/wayneeseguin/rvm/issues/3212

Warning! PATH is not properly set up, $GEM_HOME is not set,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.3.0'.
master failed to start, check stderr log for details

SSHKit::Command::Failed: sudo exit status: 1
```

of course I need to boil this down. so that it's

* not running through capistrano (I get the same error directly on the server running `sudo /etc/init.d/unicorn_my_application_ci start`

With capistrano out of the equation, I was looking into the error (same error):

```
$  sudo /etc/init.d/unicorn_my_application_ci start
/etc/init.d/unicorn_my_application_ci: line 37: kill: (24313) - No such process

Warning: PATH set to RVM ruby but GEM_HOME and/or GEM_PATH not set, see:
    https://github.com/wayneeseguin/rvm/issues/3212

Warning! PATH is not properly set up, $GEM_HOME is not set,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.3.0'.
master failed to start, check stderr log for details
```

First I read the entire thread at https://github.com/wayneeseguin/rvm/issues/3212, but it mostly seems related to zsh and not init.d scripts.

Then I suspected it could be my rvm1-capistrano3 and the capistrano-unicorn-nginx plugin

I looked at the generated file `/etc/init.d/unicorn_my_application_ci`:

```
#!/bin/bash
### BEGIN INIT INFO
# Provides: unicorn
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Manage unicorn server
# Description: Start, stop, restart unicorn server for a specific application.
### END INIT INFO
set -e

# Feel free to change any of the following variables for your app:
TIMEOUT=${TIMEOUT-60}
APP_ROOT=/var/www/my-application-test.nine.dk/current
PID=/var/www/my-application-test.nine.dk/shared/tmp/pids/unicorn.pid

AS_USER=deployer
UNICORN_ENV=""
CMD="export HOME; true "${HOME:=$(getent passwd "$AS_USER" | cut -d: -f6;)}" ; cd $APP_ROOT && $UNICORN_ENV /tmp/my-rvm-auto/rvm-auto.sh ruby-2.3.0@rails4.2 bundle exec unicorn -D -c /var/www/my-application-test.nine.dk/shared/config/unicorn.rb -E ci"

set -u

OLD_PIN="$PID.oldbin"

sig () {
  test -s "$PID" && kill -$1 `cat $PID`
}

```

(truncated). and apparently the `CMD is not good enough for picking up the rvm options it needs. OK then I read https://github.com/rvm/rvm1-capistrano3/issues/43 and tried a few of @mpapis and @rhomeister s tricks. But neither of these I could get to work.

For example, I tried the simplified 

```
CMD="cd $APP_ROOT && HOME=/home/deployer /tmp/my-rvm-auto/rvm-auto.sh ruby-2.3.0@rails4.2 bundle exec unicorn -D -c /var/www/my-application-test.nine.dk/shared/config/unicorn.rb -E ci"
```

Still failing.

Is this a problem with /tmp/my/rvm/auto/rvm/auto.sh script?

Therefore I would ask you to **share your configurations with me**. And especially, for example a minimal example that can prove that rvm loads correct ruby + gems via an init.d script.

All suggestions more than welcome. I spent my entire afternoon and evening yesterday trying to figure out this issue. Thanks!

**Comment by jesperronn** [comment]
A little progress for me: I continued to work with the init.d script on the remote machine until I could get the command to work

```
/etc/init.d/unicorn_my_application_ci
```

I found the gemset definition `ruby-2.3.0@rails4.2` to be a problem with bundler on the machine, since bundler defaults to installing dependencies in `/var/www/my-application-test.nine.dk/shared/bundle/`. 

The problem I found was that I could not generate a wrapper like this:

```
cd /var/www/my-application-test.nine.dk/current
```
rvm told me that no unicorn was found. looking in all the wrong locations:

```
which: no unicorn in 

/home/deployer/.rvm/gems/ruby-2.3.0@rails4.2/bin:
/home/deployer/.rvm/gems/ruby-2.3.0@global/bin:
/home/deployer/.rvm/rubies/ruby-2.3.0/bin:
/home/deployer/.rvm/bin:
/usr/local/bin:
/bin:
/usr/bin:
/usr/local/sbin:
/usr/sbin:
/sbin:
/opt/aws/bin:
/home/deployer/.local/bin:
/home/deployer/bin
```


So I changed this line in my `config/deploy.rb`:

```
set :rvm1_ruby_version, 'ruby-2.3.0@rails4.2'
```
to
```
set :rvm1_ruby_version, 'ruby-2.3.0'
```

And I also added
```
set :bundle_path, nil
```

Oh and then I had to 'unremember' bundle settings by deleting the folder `/var/www/my-application-test.nine.dk/current/.bundle/`.

This way, bundler will install gems in shared bundler directory for the `deploy` configuration. You can read about it in Bundler documentation (flags `--deploy` and `--path`). Essentially this means that all gems go into `/current/vendor/gems` instead.

Now with that in place, I was able to generate an rvm wrapper with the alias command:

```
cd /var/www/my-application-test.nine.dk/current/

rvm alias create my_app current
BUNDLER=/home/deployer/.rvm/wrappers/my_app/bundle

# test with
/home/deployer/.rvm/wrappers/my_app/bundle exec unicorn --version

#=> unicorn v5.0.1
```

Success! I finally am able to run a command in the context of my bundle :+1: . BTW, the example above that worked for me is what Michal Papis (rvm1-capistrano (etc.) maintainer) wrote many places. Here for instance: http://stackoverflow.com/questions/18038170/manage-sidekiq-with-init-d-script-using-rvm/18038431#18038431

Now finally, I modify my `/etc/init.d/unicorn` script to use the new wrapped bundler command:

Modified lines only (new `CMD`):
```
UNICORN_CONFIG="/var/www/my-apllication-test.nine.dk/shared/config/unicorn.rb"
ENVIRONMENT="ci"
BUNDLER="/home/deployer/.rvm/wrappers/my_app/bundle"
UNICORN="$BUNDLER exec unicorn"
CMD="export HOME=/home/$AS_USER ; cd $APP_ROOT && $UNICORN -D -c $UNICORN_CONFIG -E $ENVIRONMENT"

```

I know this gets rather long, but for the sake of humanity, if this can help  others to waste less time, then I am happy :)

**Comment by mpapis** [comment]
glad you sorted it out :)
